### ISSUE TITLE
Make the font size bigger!

### ISSUE THREAD

**Issue by zachleat** [zachleat/zachleat.com#16]
Filed here https://brignell.co/@ben/100595344952324737

![image](https://user-images.githubusercontent.com/39355/44485629-d5b99200-a616-11e8-8d71-c826d316dac1.png)

**Comment by hankchizljaw** [comment]
Ben is an award-winning designer so you should take this v seriously Zach

**Comment by zachleat** [comment]
I mean, just because Ben has won awards doesn’t mean his advice is bad

**Comment by hankchizljaw** [comment]
It's impossible for him to give bad advice because he is an award winner and rejecter of awards
