### ISSUE TITLE
Sidebar social icons FOUC

### ISSUE THREAD

**Issue by Krinkle** [zachleat/zachleat.com#20]
During most page views, I see the social icons flash with a large size and high vibrancy. After a split second or so, they shrink and the content below it pulls up along with it (the tag navigation).

Example:

<img height="158" width="441" alt="export" src="https://user-images.githubusercontent.com/156867/59238416-f4b10100-8bf5-11e9-989a-9c843960ed8d.png">

**Comment by zachleat** [comment]
This should be fixed as of last night! Thanks for reporting!
