### ISSUE TITLE
Wrong target value on Webmention input form generated

### ISSUE THREAD

**Issue by bekoli** [zachleat/zachleat.com#22]
Hej,
trying to figure out why a webmention didn't make it so I decided to post ist manually using the Webmention input form _from your site_:

![image](https://user-images.githubusercontent.com/5016428/71848497-e6658d80-30cf-11ea-8eca-d4dd92d155ae.png)

```html
<input type="hidden" name="target" value="https://www.zachleat.com/web/web/own-your-content/">
```
This results in form data with a doubled `/web` in path and can never be found on the source url resulting in a rejection of the Webmention by your endpoint.

Example result:

```
source: https://beko.famkos.net/2020/01/06/fun-introductions-to-indieweb/
target: https://www.zachleat.com/web/web/own-your-content/
```

When I fixed the target manually it went into processing (may still not make it - problems with ActivityPub plugin providing JSON instead _on my site_ are known).

**Comment by zachleat** [comment]
Ah, thank you! Fixed and deployed 👍
