### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by tannerdolby** [zachleat/zachleat.com#29]
Hi, Zach. While reading through [11ty-lighthouse](https://www.zachleat.com/web/11ty-lighthouse/), I encountered an anchor element with broken linkage (404) inside Step 2 [Fetch The Data](https://www.zachleat.com/web/11ty-lighthouse/#step-2%3A-fetch-the-data). 

The problematic link is the second anchor element with `href="https://github.com/11ty/11ty-website/blob/master/_data/speedlify.js"` and value "Eleventy data request to fetch and cache the API data at build time". 

Currently the bad URL opens [this page](https://github.com/11ty/11ty-website/blob/master/_data/speedlify.js) which shows a 404 error page on Github, where `speedlify.js` is the unavailable file.

I tried to track down the correct reference for the speedlify instance and arrived at two possible URLs.

- [speedlifyLeaderboards.js](https://github.com/11ty/11ty-website/blob/master/_data/speedlifyLeaderboards.js)
- [speedlifyStarters.js](https://github.com/11ty/11ty-website/blob/master/_data/speedlifyStarters.js)

I was going to submit a PR fixing the broken URL by using one of the two links above, but I thought I'd let you know first as I wasn't sure which link you wanted to use. Thanks! @zachleat

**Comment by zachleat** [comment]
Oh awesome—good catch, thanks! The correct one is https://github.com/11ty/11ty-website/blob/master/_data/speedlifyStarters.js

**Comment by zachleat** [comment]
Actually should probably use a URL that won’t break even if the file moves:

https://github.com/11ty/11ty-website/blob/81d5cc8f0e166ea3c2586558f60b670542f4901b/_data/speedlifyStarters.js

**Comment by tannerdolby** [comment]
No problem! I just submitted a PR that updates the old URL.

**Comment by tannerdolby** [comment]
Closing this issue. The bad URL will be fixed upon #30 being merged.
