### ISSUE TITLE
Multi-line code blocks don't have any content

### ISSUE THREAD

**Issue by tannerdolby** [zachleat/zachleat.com#33]
@zachleat I referred back to an article on [Add Lighthouse to footer](https://www.zachleat.com/web/lighthouse-in-footer/) and noticed all of the multi-line code blocks that are highlighted with Prism don't have any content within the `<code>` tags even though they indeed have content inside Markdown.

I suspect something with `{% highlight %}` is for some reason ignoring the text inside and not displaying any content within the `<code>` tags. Here is an example on [Line 36](https://github.com/zachleat/zachleat.com/blame/master/web/_posts/2020-07-12-lighthouse-in-footer.md#L36).

```
{% highlight bash %}npm install @11ty/eleventy-cache-assets --save-dev{% endhighlight %}
```
#### Screenshot of empty code block

<img width="742" alt="Screen Shot 2020-11-26 at 11 12 49 PM" src="https://user-images.githubusercontent.com/48612525/100421289-f0241680-303c-11eb-9ffc-f63423432549.png">

This issue is happening for all posts on your website at the current time (11:05pm PST). Just wanted to let you know!

**Comment by zachleat** [comment]
Oh thank you very much for the report! Looks like `{% highlight %}` is broken but the markdown version is working okay so it’s only for about 5 or so pages on the site. I’ll have a deeper look

**Comment by zachleat** [comment]
Looks like this unearthed an incompatibility with the upcoming Eleventy 1.0 and the syntax highlighter plugin. I rolled back for now to fix this and filed https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/40

Thank you!

**Comment by tannerdolby** [comment]
You're welcome Zach!
