### ISSUE TITLE
Question: Minimum NodeJS required for your repo?

### ISSUE THREAD

**Issue by inetbiz** [zachleat/zachleat.com#37]
`package.json` has
```json
"engines": {
    "node": "14"
 }
```
I'm practicing on replit.com. The template version is `14.17.1`. Can you switch that to
```json
"engines": {
  "node": ">= 14.17.1"
}
```
Might make it future-proof? Source: https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

**Comment by zachleat** [comment]
Fixed, thanks!
