### ISSUE TITLE
Feature: Modify .htaccess  to USE SED to modify the _site version to add custom 301, 410, et al

### ISSUE THREAD

**Issue by inetbiz** [zachleat/zachleat.com#38]
1.Vanilla MD with permalink into `_site`
2. Comment headers for various places to inject personal stuff.
3. a shell script containing:
```bash
#!/bin/bash
# Ask the user for new custom htaccess line
echo Section to ammend?
read append
echo Command to append?
read line
sed '/$append/a $line' ~/_site/.htaccess
```
I'm sure someone else might be able to construct the bash command to read a file to append multiple lines when section matches. This makes your repo better suited for a template; removes custom redirects, etc.
Source: https://ryanstutorials.net/bash-scripting-tutorial/bash-input.php

**Comment by zachleat** [comment]
Appreciate this! Since I moved to Netlify I no longer use .htaccess though
