### ISSUE TITLE
Overflow issue on markdown-bench-chart svg 

### ISSUE THREAD

**Issue by SavPhill** [zachleat/zachleat.com#42]
On blog post https://www.zachleat.com/web/build-benchmark/ one of the values continues to overflow vertically above the page. This is caused by `#markdown-bench-chart svg { overflow: visible; }` on Line 55. 

Recommend to adjust or even remove.

**Comment by zachleat** [comment]
Some discussion on this here https://twitter.com/zachleat/status/1553141790894596097

Feature not a bug 😅
