### ISSUE TITLE
"Cannot GET /" after install and start

### ISSUE THREAD

**Issue by nielsbom** [zachleat/zachleat.com#45]
More of an FYI but I did:

1. `git clone https://github.com/zachleat/zachleat.com.git`
2. `npm i && npm start`
3. Opened http://localhost:8090/

Got `Cannot GET /` in browser and no errors on the command line.

(Node 18.5.0 btw)

**Comment by zachleat** [comment]
Hmm, not quite sure why this happened. I did do a fresh install and was not able to reproduce this.

Appreciate the report though!
