### ISSUE TITLE
The video from Smashing Conference Freiburg is up?

### ISSUE THREAD

**Issue by azangru** [zachleat/zachleat.com#51]
From [`2024-01-31-good-bad-web-components.md`](https://github.com/zachleat/zachleat.com/blame/13f0d91a591f1cf2965393e1366c5101487e8b26/_posts/2024-01-31-good-bad-web-components.md#L355-L355C103):

> * [Smashing Conference Freiburg](/web/smashingconf/2023/) (September 2023) _(video not yet available)_

It seems like it is. It has been released 2 months ago.

https://www.youtube.com/watch?v=1UPSJRnSzmw

**Comment by zachleat** [comment]
Ah, thank you! The build is updating with that video. Somehow I missed it, I thought they were still going to Vimeo but obviously not https://vimeo.com/channels/smashingconf/videos
