### ISSUE TITLE
b, g, p looks wrong in Lato on IE9/Windows 7

### ISSUE THREAD

**Issue by zachleat** [zachleat/zachleat.com#6]
Also on Opera/Window 7

https://twitter.com/RichardCarter/status/559036795477032960

**Comment by simevidas** [comment]
Firefox on Windows 8.1
![capture](https://cloud.githubusercontent.com/assets/716405/5895525/b3aaa350-a522-11e4-84d2-93596c45566f.PNG)

**Comment by zachleat** [comment]
Yeah, unfortunately this has made me realize that my caching for the font files isn’t quite right. If you reload, it’ll look ok. (Confirmed ok in Firefox/Windows 8.1 in Browserstack)
