### ISSUE TITLE
Experimental `@font-display` support in Firefox

### ISSUE THREAD

**Issue by myakura** [zachleat/zachleat.com#9]
In https://github.com/zachleat/zachleat.com/blob/135bf9b3fc103cfa97dc94ddf2fed27a3de1ad72/web/_posts/2016-07-12-comprehensive-fontloading.md#cons-1 it says:

> No stable browser support. Only Chrome Platform Status has a status page for it. It isn’t documented on Firefox Platform Status or Edge Platform Status.

Yet it's not stable, Firefox appears to support it since Firefox 46 https://bugzilla.mozilla.org/show_bug.cgi?id=1157064

**Comment by zachleat** [comment]
@myakura Is that true? I just ran a test locally with `font-display: swap` and `font-display: optional` and neither performed as expected.

See the following from `about:config`:
![image](https://cloud.githubusercontent.com/assets/39355/17010102/6ef46f62-4ec6-11e6-8040-dcc33667b0a6.png)

What does yours say there?

**Comment by myakura** [comment]
ah, yes. Mozilla _implements_ the descriptor but hasn't shipped it yet. you have to turn it on via about:config. my bad.

what I meant was I wanted to say there is an interest from Mozilla even though there is no status entry on the platform status page.

**Comment by zachleat** [comment]
Great! For my own future reference I’ll be looking for it here https://platform-status.mozilla.org/

**Comment by vijayaraghavanramanan** [comment]
Excellent. Seems to be working well in Nightly.
